import { test, expect } from '@playwright/test'

async function consent(page,value='analytics'){
  await page.addInitScript((choice)=>{
    localStorage.setItem('vora_consent',choice)
    window.recordedEvents=[]
    window.gtag=(...args)=>window.recordedEvents.push(args)
  },value)
}

test('small iPhone hero keeps message and primary action inside the first viewport',async({page})=>{
  await consent(page,'necessary')
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.setViewportSize({width:320,height:568})
  await page.goto('/')
  const header=await page.locator('header').boundingBox()
  const title=await page.locator('#top h1').boundingBox()
  const primary=await page.getByRole('link',{name:'Descubrir la colección'}).boundingBox()
  const secondary=await page.getByRole('link',{name:'Cómo funciona VORA'}).boundingBox()
  expect(title.y).toBeGreaterThan(header.y+header.height)
  expect(primary.y+primary.height).toBeLessThanOrEqual(568)
  expect(secondary.y+secondary.height).toBeLessThanOrEqual(568)
  await expect(page.getByRole('button',{name:'Abrir menú'})).toHaveCSS('width','44px')
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  expect(await page.locator('#contact input').first().evaluate(element=>getComputedStyle(element).fontSize)).toBe('18px')
})

test('compact collection exposes view and configure actions without losing state',async({page})=>{
  await consent(page)
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.setViewportSize({width:320,height:568})
  await page.goto('/#models')
  const collection=page.locator('#models')
  await expect(collection.locator('article')).toHaveCount(7)
  expect((await collection.boundingBox()).height).toBeLessThan(2600)
  await page.evaluate(()=>{window.phaseSevenIdentity=Math.random()})
  const identity=await page.evaluate(()=>window.phaseSevenIdentity)
  await collection.locator('article').nth(2).getByRole('link',{name:'Configurar'}).click()
  expect(await page.evaluate(()=>window.phaseSevenIdentity)).toBe(identity)
  await expect(page).toHaveURL(/model=130.*source=model-collection.*#configurator/)
  await expect(page.getByRole('group',{name:'01 · MODELO'}).getByRole('button',{name:'130',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'Hablar de esta VORA'}).click()
  await expect(page.getByRole('region',{name:'TU SELECCIÓN DEL CONFIGURADOR'})).toContainText('VORA 130')
  await expect(page).toHaveURL(/source=model-collection.*#contact/)
})

test('plan can be expanded, panned and zoomed with keyboard-safe controls',async({page})=>{
  await consent(page,'necessary')
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.setViewportSize({width:390,height:844})
  await page.goto('/modelos/vora-130#plan')
  await page.locator('#plan').scrollIntoViewIfNeeded()
  await expect.poll(()=>page.locator('[data-mobile-model-cta]').count()).toBe(0)
  const expand=page.locator('#plan').getByRole('button',{name:'Ampliar plano'})
  await expand.click()
  const dialog=page.getByRole('dialog',{name:'VORA 130'})
  await expect(dialog).toBeVisible()
  await expect(dialog.getByRole('button',{name:'Cerrar plano ampliado'})).toBeFocused()
  await expect(page.locator('body')).toHaveCSS('overflow','hidden')
  expect(await dialog.locator('[data-lenis-prevent]').evaluate(element=>element.scrollWidth>element.clientWidth)).toBe(true)
  await expect(dialog.getByRole('status')).toHaveText('125%')
  await dialog.getByRole('button',{name:'Ampliar plano'}).click()
  await expect(dialog.getByRole('status')).toHaveText('150%')
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(expand).toBeFocused()
  await expect(page.locator('body')).not.toHaveCSS('overflow','hidden')
})

test('model content order prioritizes the plan and persistent CTA avoids interactive sections',async({page})=>{
  await consent(page,'necessary')
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.setViewportSize({width:390,height:844})
  await page.goto('/modelos/vora-170')
  const order=await page.evaluate(()=>['section[aria-label^="Datos principales"]','#plan','section[aria-labelledby="features-title"]','#configurator','#contact'].map(selector=>document.querySelector(selector).getBoundingClientRect().top+scrollY))
  expect(order).toEqual([...order].sort((a,b)=>a-b))
  await expect(page.locator('[data-mobile-model-cta]')).toBeVisible()
  await page.locator('section[aria-labelledby="features-title"]').scrollIntoViewIfNeeded()
  await expect.poll(()=>page.locator('[data-mobile-model-cta]').count()).toBe(0)
})

test('SEO landing offers a direct configure path and preserves its source',async({page})=>{
  await consent(page)
  await page.emulateMedia({reducedMotion:'reduce'})
  await page.setViewportSize({width:390,height:844})
  await page.goto('/casas-industrializadas-hormigon')
  const model=page.getByRole('article').filter({has:page.getByRole('heading',{name:'VORA 130'})})
  await model.getByRole('link',{name:'Configurar'}).click()
  await expect(page).toHaveURL(/model=130.*source=seo-landing.*#configurator/)
  await expect(page.getByRole('group',{name:'01 · MODELO'}).getByRole('button',{name:'130',exact:true})).toHaveAttribute('aria-pressed','true')
  await page.getByRole('button',{name:'Hablar de esta VORA'}).click()
  await expect(page.getByRole('region',{name:'TU SELECCIÓN DEL CONFIGURADOR'})).toContainText('VORA 130')
  await expect(page).toHaveURL(/source=seo-landing.*#contact/)
})
