import { useEffect } from 'react'
import { ArrowLeft, ArrowUpRight, BedDouble, Bath, Ruler, House } from 'lucide-react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import PlanTabs from '../components/PlanTabs'
import { HOUSES } from '../data/houses'
import { track } from '../lib/analytics'

const INCLUDED=['Cocina completa','Electrodomésticos integrados','Salón amueblado','Dormitorios equipados','Baños terminados','Iluminación','Climatización','Armarios e instalaciones']
export default function ModelPage({model}){
  useEffect(()=>{track('view_model',{model:model.id,surface:model.size});window.scrollTo(0,0)},[model.id])
  const related=HOUSES.filter(h=>h.id!==model.id).slice(0,3)
  return <><Navbar forceLight/><main className="bg-cream-200 text-navy-700">
    <section className="relative min-h-[92svh] bg-navy-800 text-cream-200 overflow-hidden"><img src={model.image} alt={`Exterior VORA ${model.name}`} className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-navy-900/85 via-navy-900/10 to-navy-900/20"/><div className="relative z-10 min-h-[92svh] max-w-[1600px] mx-auto px-6 md:px-12 pt-28 pb-10 flex flex-col justify-between"><a href="/#models" className="inline-flex items-center gap-2 text-sm text-cream-200/75 hover:text-cream-200"><ArrowLeft size={15}/> Volver a la colección</a><div className="grid grid-cols-12 gap-6 items-end"><div className="col-span-12 lg:col-span-8"><div className="section-label text-gold-200 mb-5">{model.code} · {model.tag}</div><h1 className="font-display text-[clamp(5.5rem,14vw,14rem)] leading-[.72] tracking-[-.07em]">{model.name}</h1><p className="mt-7 font-display text-2xl md:text-4xl max-w-3xl leading-tight">{model.statement}</p></div><div className="col-span-12 lg:col-span-4 lg:text-right"><p className="section-label text-cream-200/65">{model.size} · {model.bedrooms} dormitorios · {model.bathrooms} baños</p><a href="#plan" className="mt-6 inline-flex items-center gap-2 text-sm link-underline">Ver distribución <ArrowUpRight size={14}/></a></div></div></div></section>

    <section className="py-20 md:py-36 max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-6 md:gap-10"><div className="col-span-12 md:col-span-4 section-label text-navy-700/45">ARQUITECTURA / {model.code}</div><div className="col-span-12 md:col-span-8"><h2 className="font-display text-display leading-[.95] tracking-tightest">Una casa diseñada para que <em className="italic text-gold-400 font-light">todo encaje</em>.</h2><p className="mt-8 md:mt-12 text-lg md:text-2xl leading-relaxed text-navy-700/72 max-w-3xl">{model.narrative}</p><p className="mt-6 text-navy-700/60 max-w-2xl">{model.idealFor}</p></div></div></section>

    <section className="px-3 md:px-6 pb-3 md:pb-6"><div className="grid grid-cols-12 gap-3 md:gap-6 max-w-[1800px] mx-auto"><figure className="col-span-12 lg:col-span-7 aspect-[16/11] overflow-hidden"><img src={model.image} alt={`Fachada y jardín VORA ${model.name}`} className="w-full h-full object-cover"/></figure><figure className="col-span-12 lg:col-span-5 aspect-[4/5] overflow-hidden"><img src={model.interior} alt={`Interior VORA ${model.name}`} className="w-full h-full object-cover"/></figure></div></section>

    <section className="py-20 md:py-32 bg-navy-800 text-cream-200"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-2 lg:grid-cols-4 border-t border-l border-cream-200/12"><Spec icon={House} label="Superficie" value={model.size}/><Spec icon={BedDouble} label="Dormitorios" value={String(model.bedrooms).padStart(2,'0')}/><Spec icon={Bath} label="Baños" value={String(model.bathrooms).padStart(2,'0')}/><Spec icon={Ruler} label="Porche" value={`${model.porchSurface} m²`}/></div></div></section>

    <section id="plan" className="py-20 md:py-36 max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-8"><div className="col-span-12 md:col-span-4"><div className="section-label text-gold-400 mb-5">PLANO CONCEPTUAL</div><h2 className="font-display text-4xl md:text-6xl tracking-tightest leading-[.95]">{model.usableSurface} m² útiles.<br/><em className="italic text-gold-400 font-light">Sin metros perdidos.</em></h2><p className="mt-6 text-navy-700/65">Dimensiones exteriores: {model.dimensions}</p></div><div className="col-span-12 md:col-span-8"><PlanTabs plan={model.plan}/><p className="mt-4 text-xs text-navy-700/45">Distribución orientativa sujeta a adaptación técnica, urbanística y estructural.</p></div></div><div className="mt-12 md:mt-16 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 border-t border-l border-navy-700/10">{model.rooms.map(room=><div key={room.name} className="p-5 border-r border-b border-navy-700/10 flex justify-between gap-4"><span>{room.name}</span><span className="font-mono text-sm text-navy-700/55">{room.area.toFixed(1).replace('.',',')} m²</span></div>)}</div></section>

    <section className="py-20 md:py-36 bg-navy-700 text-cream-200"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-6"><div className="col-span-12 md:col-span-4 section-label text-gold-300">READY TO LIVE</div><div className="col-span-12 md:col-span-8"><h2 className="font-display text-display leading-[.95] tracking-tightest">Cuando recibes las llaves,<br/><em className="italic text-gold-300 font-light">la casa está terminada.</em></h2><div className="grid grid-cols-2 md:grid-cols-4 gap-x-7 mt-12">{INCLUDED.map((item,i)=><div key={item} className="py-5 border-t border-cream-200/12"><div className="section-label text-gold-300 mb-2">{String(i+1).padStart(2,'0')}</div><div>{item}</div></div>)}</div></div></div></div></section>

    <section className="concrete-surface py-24 md:py-36"><div className="relative z-10 max-w-[1600px] mx-auto px-6 md:px-12 grid grid-cols-12 gap-6 items-end"><div className="col-span-12 lg:col-span-8"><div className="section-label text-navy-700/50 mb-5">VORA {model.name}</div><h2 className="font-display text-display leading-[.9] tracking-tightest">¿Encaja en tu parcela?</h2><p className="mt-6 text-lg text-navy-700/65 max-w-2xl">El siguiente paso no es rediseñar la casa: es comprobar que este modelo encaja técnica y urbanísticamente en tu solar.</p></div><div className="col-span-12 lg:col-span-4 lg:text-right"><a href={`/?model=${encodeURIComponent(model.name)}#contact`} onClick={()=>track('cta_click',{cta:'study_plot',model:model.id})} className="btn-primary"><span>Estudiar mi parcela</span><ArrowUpRight size={16}/></a></div></div></section>

    <section className="py-20 md:py-28 max-w-[1600px] mx-auto px-6 md:px-12"><div className="section-label text-navy-700/45 mb-8">OTROS MODELOS</div><div className="grid md:grid-cols-3 gap-6">{related.map(h=><a key={h.id} href={`/modelos/${h.id}`} className="group"><div className="aspect-[4/3] overflow-hidden"><img src={h.image} alt={`VORA ${h.name}`} className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-[1.03]"/></div><div className="mt-4 flex justify-between"><span className="font-display text-3xl">VORA {h.name}</span><span className="section-label text-navy-700/45">{h.size}</span></div></a>)}</div></section>
  </main><Footer/><a href={`/?model=${encodeURIComponent(model.name)}#contact`} className="fixed md:hidden bottom-3 left-3 right-3 z-50 bg-navy-800 text-cream-200 rounded-full px-5 py-4 flex items-center justify-between shadow-2xl"><span className="text-sm">VORA {model.name}</span><strong className="text-xs uppercase tracking-[.14em]">Estudiar parcela →</strong></a></>
}
function Spec({icon:Icon,label,value}){return <div className="min-h-[170px] md:min-h-[210px] border-r border-b border-cream-200/12 p-5 md:p-8 flex flex-col justify-between"><div className="flex justify-between"><div className="section-label text-cream-200/45">{label}</div><Icon size={18} className="text-gold-300"/></div><div className="font-display text-5xl md:text-7xl tracking-tightest">{value}</div></div>}
