import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { HOUSES } from '../data/houses'
import { LANDING_PAGES } from '../data/siteContent'
import { ArrowUpRight, Check } from 'lucide-react'
import { analyticsFunnelKey, track, trackOnce } from '../lib/analytics'

export default function SearchLanding({slug}){
  const p=LANDING_PAGES[slug]||LANDING_PAGES['casas-industrializadas-hormigon']
  const featured=p.featuredIds.map((id)=>HOUSES.find((house)=>house.id===id)).filter(Boolean)
  const contact=()=>{
    track('contact_cta_click',{cta:'seo_landing_contact',source:'seo-landing',placement:slug,has_configuration:false})
    trackOnce(analyticsFunnelKey('contact-start','seo-landing'),'contact_start',{source:'seo-landing',placement:slug,has_configuration:false})
  }
  return <><Navbar forceLight/><main className="bg-cream-200 text-navy-700">
    <section className="pt-32 md:pt-40 pb-20 md:pb-28"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><nav aria-label="Migas de pan" className="mb-8 text-sm text-navy-700/60"><ol className="flex flex-wrap items-center gap-2"><li><a href="/" className="link-underline">Inicio</a></li><li aria-hidden="true">/</li><li aria-current="page">{p.eyebrow}</li></ol></nav><div className="grid grid-cols-12 gap-8"><div className="col-span-12 md:col-span-8"><div className="section-label text-gold-400 mb-6">{p.eyebrow}</div><h1 className="font-display text-[clamp(3.3rem,7vw,8rem)] leading-[.92] tracking-tightest">{p.title}</h1><p className="mt-8 text-lg md:text-2xl text-navy-700/68 leading-relaxed max-w-3xl">{p.lead}</p><a href={`/?source=seo-landing#contact`} onClick={contact} className="btn-primary mt-9"><span>Hablar de mi proyecto</span><ArrowUpRight size={16}/></a></div><div className="col-span-12 md:col-span-4 md:pt-14"><ul className="border-t border-navy-700/10">{p.bullets.map(x=><li key={x} className="py-4 border-b border-navy-700/10 flex gap-3"><Check size={16} className="text-gold-400 mt-1 flex-none" aria-hidden="true"/><span>{x}</span></li>)}</ul></div></div></div></section>
    <section className="px-3 md:px-6" aria-label="Arquitectura VORA"><div className="max-w-[1800px] mx-auto aspect-[16/8] md:aspect-[21/8] overflow-hidden"><img src={p.image} alt={p.imageAlt} loading="lazy" decoding="async" className="w-full h-full object-cover"/></div></section>
    <section className="py-24 md:py-36 max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-8"><div className="col-span-12 md:col-span-4 section-label text-navy-700/45">POR QUÉ VORA</div><div className="col-span-12 md:col-span-8"><h2 className="font-display text-display leading-[.95] tracking-tightest">{p.valueTitle}</h2><div className="mt-10 grid md:grid-cols-2 gap-6 text-lg text-navy-700/68">{p.valueParagraphs.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}</div></div></div></section>
    <section className="py-24 md:py-32 bg-navy-700 text-cream-200"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><div className="section-label text-gold-300 mb-8">MODELOS DESTACADOS</div><div className="grid md:grid-cols-3 gap-7">{featured.map(h=><article key={h.id} className="group"><a href={`/modelos/${h.id}`} onClick={()=>track('select_model',{model:h.id,source:'seo-landing',placement:slug})}><div className="aspect-[16/10] md:aspect-[4/3] overflow-hidden"><img src={h.image} alt={`VORA ${h.name}`} loading="lazy" decoding="async" className="w-full h-full object-cover transition-transform duration-700 motion-reduce:transition-none group-hover:scale-[1.03]"/></div><div className="mt-4 flex justify-between items-start"><div><h2 className="font-display text-4xl">VORA {h.name}</h2><div className="mt-2 text-cream-200/55 text-sm">{h.bedrooms} dormitorios · {h.bathrooms} baños</div></div><ArrowUpRight className="text-gold-300" aria-hidden="true"/></div></a><div className="mt-4 grid grid-cols-2 gap-2"><a href={`/modelos/${h.id}`} onClick={()=>track('select_model',{model:h.id,source:'seo-landing',placement:`${slug}_action`})} className="min-h-11 rounded-full border border-cream-200/20 px-3 inline-flex items-center justify-center text-xs">Ver modelo</a><a href={`/?model=${encodeURIComponent(h.name)}&source=seo-landing#configurator`} onClick={()=>trackOnce(analyticsFunnelKey('configurator-start','seo-landing',h.id),'configurator_start',{source:'seo-landing',model:h.id,placement:slug})} className="min-h-11 rounded-full bg-cream-200 text-navy-700 px-3 inline-flex items-center justify-center text-xs">Configurar</a></div></article>)}</div><a href="/#compare" className="mt-10 min-h-11 inline-flex items-center gap-2 text-sm link-underline">Comparar los siete modelos <ArrowUpRight size={14}/></a></div></section>
    <section aria-labelledby="faq-title" className="py-24 md:py-32 max-w-[1200px] mx-auto px-6 md:px-12"><div className="section-label text-gold-400 mb-4">PREGUNTAS CLAVE</div><h2 id="faq-title" className="font-display text-4xl md:text-6xl tracking-tightest">Antes de elegir tu VORA.</h2><div className="mt-8 divide-y divide-navy-700/10">{p.faqs.map(({question,answer})=><article key={question} className="py-7 grid md:grid-cols-12 gap-4"><h3 className="md:col-span-5 font-display text-2xl">{question}</h3><p className="md:col-span-7 text-navy-700/65 leading-relaxed">{answer}</p></article>)}</div><div className="mt-12"><a href="/?source=seo-landing#contact" onClick={contact} className="btn-primary"><span>Hablar de mi proyecto</span><ArrowUpRight size={16}/></a></div></section>
  </main><Footer/></>
}
