import useMediaQuery from '../hooks/useMediaQuery'
import { useEffect, useRef } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import SplitType from 'split-type'
import { Check } from 'lucide-react'
import { CONFIRMED_SCOPE_ITEMS, SCOPE_STATUS_LABELS } from '../data/businessContent'

gsap.registerPlugin(ScrollTrigger)
const STORIES=[
  {eyebrow:'COCINA',title:'La cocina.',copy:'Diseñada, instalada y equipada. Mobiliario, encimera y electrodomésticos forman parte de la casa.',image:'/media/houses/model-03-interior.webp'},
  {eyebrow:'LIVING',title:'El sofá.',copy:'El salón no se entrega vacío. Llega amueblado para que el espacio se sienta terminado desde el primer día.',image:'/media/houses/model-06-interior.webp'},
  {eyebrow:'DORMITORIOS',title:'La cama.',copy:'Dormitorios preparados para vivirlos: mobiliario esencial, armarios e iluminación dentro de una misma propuesta.',image:'/media/houses/model-02-interior.webp'},
  {eyebrow:'BAÑOS',title:'Hasta el último detalle.',copy:'Baños terminados, climatización, iluminación e instalaciones. No entregamos metros; entregamos la casa.',image:'/media/houses/model-07-interior.webp'},
]
export default function Benefits(){
  const reducedMotion=useMediaQuery('(prefers-reduced-motion: reduce)')
const sectionRef=useRef(null),headingRef=useRef(null);useEffect(()=>{const ctxSplitCleanup=[];const ctx=gsap.context(()=>{if(reducedMotion)return;const split=new SplitType(headingRef.current,{types:'lines,words',lineClass:'reveal-line'});ctxSplitCleanup.push(()=>split.revert());gsap.set(split.words,{yPercent:110});ScrollTrigger.create({trigger:headingRef.current,start:'top 80%',onEnter:()=>gsap.to(split.words,{yPercent:0,duration:1.2,ease:'expo.out',stagger:.035})});sectionRef.current.querySelectorAll('[data-story]').forEach(el=>gsap.from(el,{opacity:0,y:50,duration:1.1,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 80%'}}))},sectionRef);return()=>{ctx.revert();ctxSplitCleanup.forEach(cleanup=>cleanup())}},[reducedMotion]);return <section id="included" ref={sectionRef} className="bg-navy-700 text-cream-200 py-24 md:py-40 overflow-hidden"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-4 md:gap-8 mb-16 md:mb-24"><div className="col-span-12 md:col-span-4 section-label text-cream-200/50"><span className="text-gold-300">03</span> / 07 — QUÉ INCLUYE</div><div className="col-span-12 md:col-span-8"><h2 ref={headingRef} className="font-display text-display leading-[.95] tracking-tightest">Terminada, equipada<br/><em className="italic text-gold-300 font-light">y amueblada.</em></h2><p className="mt-8 max-w-xl text-cream-200/70 text-lg">La propuesta ready to live reúne arquitectura, equipamiento y mobiliario en una casa preparada para vivir.</p></div></div>
    <div className="space-y-4 md:space-y-6">{STORIES.map((s,i)=><article key={s.eyebrow} data-story className="grid grid-cols-12 gap-4 md:gap-6 items-stretch"><div className={`${i%2?'md:order-2':''} col-span-12 md:col-span-7 aspect-[16/10] overflow-hidden`}><img src={s.image} alt={`${s.eyebrow.toLowerCase()} incluido en las viviendas VORA`} className="w-full h-full object-cover" loading="lazy" decoding="async"/></div><div className={`${i%2?'md:order-1':''} col-span-12 md:col-span-5 border border-cream-200/10 p-7 md:p-10 flex flex-col justify-between min-h-[300px]`}><div className="section-label text-gold-300">{String(i+1).padStart(2,'0')} · {s.eyebrow}</div><div><h3 className="font-display text-5xl md:text-7xl tracking-tightest mb-5">{s.title}</h3><p className="text-cream-200/65 text-lg leading-relaxed max-w-md">{s.copy}</p></div></div></article>)}</div>
    <div className="mt-16 md:mt-24 border-t border-cream-200/15 pt-8"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><div className="section-label text-gold-300">ALCANCE CONFIRMADO</div><h3 className="mt-3 font-display text-4xl md:text-6xl tracking-tightest">Elementos integrados en la propuesta.</h3></div><p className="max-w-md text-sm leading-relaxed text-cream-200/55">La configuración concreta se define a partir del modelo y de las opciones seleccionadas.</p></div><dl className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 border-t border-l border-cream-200/12">{CONFIRMED_SCOPE_ITEMS.map(item=><div key={item.id} className="min-h-36 border-r border-b border-cream-200/12 p-5 md:p-6"><dt className="flex items-center justify-between gap-3"><span className="font-display text-2xl">{item.name}</span><span className="inline-flex items-center gap-1.5 rounded-full border border-gold-300/35 px-2.5 py-1 text-[10px] uppercase tracking-[.14em] text-gold-200"><Check size={12} aria-hidden="true"/> {SCOPE_STATUS_LABELS[item.status]}</span></dt><dd className="mt-4 text-sm leading-relaxed text-cream-200/60">{item.detail}</dd></div>)}</dl></div>
  </div></section>}
