import { useEffect, useRef } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import SplitType from 'split-type'

gsap.registerPlugin(ScrollTrigger)
const STORIES=[
  {eyebrow:'COCINA',title:'La cocina.',copy:'Diseñada, instalada y equipada. Mobiliario, encimera y electrodomésticos forman parte de la casa.',image:'/media/houses/model-03-interior.webp'},
  {eyebrow:'LIVING',title:'El sofá.',copy:'El salón no se entrega vacío. Llega amueblado para que el espacio se sienta terminado desde el primer día.',image:'/media/houses/model-06-interior.webp'},
  {eyebrow:'DORMITORIOS',title:'La cama.',copy:'Dormitorios preparados para vivirlos: mobiliario esencial, armarios e iluminación dentro de una misma propuesta.',image:'/media/houses/model-02-interior.webp'},
  {eyebrow:'BAÑOS',title:'Hasta el último detalle.',copy:'Baños terminados, climatización, iluminación e instalaciones. No entregamos metros; entregamos la casa.',image:'/media/houses/model-07-interior.webp'},
]
export default function Benefits(){const sectionRef=useRef(null),headingRef=useRef(null);useEffect(()=>{const ctx=gsap.context(()=>{const split=new SplitType(headingRef.current,{types:'lines,words',lineClass:'reveal-line'});gsap.set(split.words,{yPercent:110});ScrollTrigger.create({trigger:headingRef.current,start:'top 80%',onEnter:()=>gsap.to(split.words,{yPercent:0,duration:1.2,ease:'expo.out',stagger:.035})});sectionRef.current.querySelectorAll('[data-story]').forEach(el=>gsap.from(el,{opacity:0,y:50,duration:1.1,ease:'expo.out',scrollTrigger:{trigger:el,start:'top 80%'}}))},sectionRef);return()=>ctx.revert()},[]);return <section id="included" ref={sectionRef} className="bg-navy-700 text-cream-200 py-24 md:py-40 overflow-hidden"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-4 md:gap-8 mb-16 md:mb-24"><div className="col-span-12 md:col-span-4 section-label text-cream-200/50"><span className="text-gold-300">03</span> / 07 — TODO INCLUIDO</div><div className="col-span-12 md:col-span-8"><h2 ref={headingRef} className="font-display text-display leading-[.95] tracking-tightest">Cuando te damos las llaves,<br/><em className="italic text-gold-300 font-light">solo faltas tú.</em></h2><p className="mt-8 max-w-xl text-cream-200/70 text-lg">Construida. Terminada. Equipada. Amueblada. VORA lleva el concepto llave en mano un paso más allá.</p></div></div>
    <div className="space-y-4 md:space-y-6">{STORIES.map((s,i)=><article key={s.eyebrow} data-story className="grid grid-cols-12 gap-4 md:gap-6 items-stretch"><div className={`${i%2?'md:order-2':''} col-span-12 md:col-span-7 aspect-[16/10] overflow-hidden`}><img src={s.image} alt={`${s.eyebrow.toLowerCase()} incluido en las viviendas VORA`} className="w-full h-full object-cover" loading="lazy"/></div><div className={`${i%2?'md:order-1':''} col-span-12 md:col-span-5 border border-cream-200/10 p-7 md:p-10 flex flex-col justify-between min-h-[300px]`}><div className="section-label text-gold-300">{String(i+1).padStart(2,'0')} · {s.eyebrow}</div><div><h3 className="font-display text-5xl md:text-7xl tracking-tightest mb-5">{s.title}</h3><p className="text-cream-200/65 text-lg leading-relaxed max-w-md">{s.copy}</p></div></div></article>)}</div>
  </div></section>}
