import { useEffect, useRef, useState } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import SplitType from 'split-type'
import { ArrowUpRight, Check } from 'lucide-react'
import { HOUSES } from '../data/houses'
import { BRAND } from '../config/brand'
import { getAttribution, track } from '../lib/analytics'

gsap.registerPlugin(ScrollTrigger)
const PLOT_OPTIONS=['Sí','La estoy buscando','No']

export default function Contact(){
  const sectionRef=useRef(null),headingRef=useRef(null); const [status,setStatus]=useState('idle'),[error,setError]=useState('')
  const [form,setForm]=useState({name:'',phone:'',email:'',province:'',plot:'',model:'',privacy:false,website:''})
  useEffect(()=>{const params=new URLSearchParams(window.location.search);setForm(f=>({...f,model:params.get('model')||f.model}));const ctx=gsap.context(()=>{const split=new SplitType(headingRef.current,{types:'lines,words',lineClass:'reveal-line'});gsap.set(split.words,{yPercent:110});ScrollTrigger.create({trigger:headingRef.current,start:'top 80%',onEnter:()=>gsap.to(split.words,{yPercent:0,duration:1.2,ease:'expo.out',stagger:.035})})},sectionRef);return()=>ctx.revert()},[])
  const change=e=>{if(status==='idle')track('form_start',{form:'lead'});const {name,type,checked,value}=e.target;setForm(f=>({...f,[name]:type==='checkbox'?checked:value}))}
  const submit=async(e)=>{e.preventDefault();setStatus('sending');setError('');try{const params=new URLSearchParams(window.location.search);const payload={...form,interior:params.get('interior')||'',exterior:params.get('exterior')||'',attribution:getAttribution(),page:window.location.href};const res=await fetch(BRAND.leadEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('No se pudo enviar');setStatus('sent');track('generate_lead',{model:form.model||'unspecified',province:form.province,has_plot:form.plot})}catch(err){setStatus('error');setError('No hemos podido enviar la solicitud. Inténtalo de nuevo en unos instantes.')}}
  if(status==='sent') return <section id="contact" className="py-28 md:py-40 bg-navy-800 text-cream-200"><div className="max-w-[1100px] mx-auto px-6 md:px-12"><div className="w-12 h-12 rounded-full border border-gold-300 flex items-center justify-center text-gold-300 mb-8"><Check/></div><div className="section-label text-gold-300 mb-4">SOLICITUD RECIBIDA</div><h2 className="font-display text-display leading-[.95] tracking-tightest">Gracias, {form.name.split(' ')[0]||'nos ponemos en marcha'}.</h2><p className="mt-7 text-lg text-cream-200/65 max-w-xl">Revisaremos el modelo y la información de tu parcela para orientar el siguiente paso.</p></div></section>
  return <section id="contact" ref={sectionRef} className="relative py-24 md:py-40 bg-navy-800 text-cream-200 overflow-hidden"><div className="max-w-[1600px] mx-auto px-6 md:px-12"><div className="grid grid-cols-12 gap-4 md:gap-8 mb-12 md:mb-20"><div className="col-span-12 md:col-span-4"><div className="section-label text-cream-200/50"><span className="text-gold-300">07</span> / 07 — SIGUIENTE PASO</div></div><div className="col-span-12 md:col-span-8"><h2 ref={headingRef} className="font-display text-display leading-[.95] tracking-tightest">Estudiemos<br/><em className="italic text-gold-300 font-light">tu parcela.</em></h2><p className="mt-8 max-w-xl text-cream-200/70 text-lg">Cuéntanos dónde quieres construir y qué VORA te interesa. Comprobaremos el encaje inicial del modelo.</p></div></div>
    <div className="grid grid-cols-12 gap-8 md:gap-12"><form onSubmit={submit} className="col-span-12 md:col-span-8 border-t border-cream-200/10"><Field label="Nombre" name="name" value={form.name} onChange={change} required/><Field label="Teléfono" name="phone" type="tel" value={form.phone} onChange={change} required/><Field label="Email" name="email" type="email" value={form.email} onChange={change}/><Field label="Provincia" name="province" value={form.province} onChange={change} required/>
      <Selector label="¿Tienes parcela?" options={PLOT_OPTIONS} value={form.plot} onSelect={v=>setForm(f=>({...f,plot:v}))}/><Selector label="Modelo" options={HOUSES.map(h=>h.name)} value={form.model} prefix="VORA " onSelect={v=>setForm(f=>({...f,model:v}))}/>
      <input type="text" name="website" value={form.website} onChange={change} className="hidden" tabIndex="-1" autoComplete="off" aria-hidden="true"/>
      <label className="flex gap-3 mt-7 text-sm text-cream-200/55 max-w-xl"><input type="checkbox" name="privacy" checked={form.privacy} onChange={change} required className="mt-1 accent-[#9A8978]"/><span>Acepto la <a href="/legal/privacidad" className="underline hover:text-cream-200">política de privacidad</a> y el tratamiento de mis datos para atender la solicitud.</span></label>
      <div className="pt-8"><button disabled={status==='sending'} type="submit" className="group inline-flex items-center gap-3 px-9 py-4 rounded-full bg-gold-400 text-cream-200 font-medium text-sm uppercase tracking-widest hover:bg-cream-200 hover:text-navy-700 transition-colors disabled:opacity-50"><span>{status==='sending'?'Enviando…':'Solicitar estudio'}</span><ArrowUpRight size={16}/></button>{status==='error'&&<p className="mt-4 text-sm text-red-200">{error}</p>}</div>
    </form><aside className="col-span-12 md:col-span-4 md:pl-10 border-t md:border-t-0 md:border-l border-cream-200/10 pt-8 md:pt-0"><div className="section-label text-gold-300 mb-4">VORA · CONCRETE LIVING</div><p className="font-display text-3xl md:text-4xl leading-tight">No te pediremos que rediseñes una casa desde cero.</p><p className="mt-6 text-cream-200/60 leading-relaxed">Partimos del modelo elegido y estudiamos su adaptación técnica, urbanística y estructural a tu parcela.</p><div className="mt-10 pt-6 border-t border-cream-200/10 section-label text-cream-200/45">{BRAND.location}</div></aside></div>
  </div></section>
}
function Field({label,name,type='text',value,onChange,required}){return <div className="py-6 border-b border-cream-200/10 grid grid-cols-12 gap-4 items-center"><label htmlFor={name} className="col-span-12 md:col-span-4 section-label text-cream-200/50">{label}{required&&<span className="text-gold-300"> *</span>}</label><input id={name} name={name} type={type} value={value} onChange={onChange} required={required} className="col-span-12 md:col-span-8 bg-transparent text-cream-200 text-lg focus:outline-none"/></div>}
function Selector({label,options,value,onSelect,prefix=''}){return <div className="py-6 border-b border-cream-200/10 grid grid-cols-12 gap-4 items-start"><div className="col-span-12 md:col-span-4 section-label text-cream-200/50 pt-2">{label}</div><div className="col-span-12 md:col-span-8 flex flex-wrap gap-2">{options.map(opt=><button key={opt} type="button" onClick={()=>onSelect(opt)} className={`px-4 py-2 rounded-full border text-sm transition-all ${value===opt?'bg-gold-400 border-gold-400':'border-cream-200/20 hover:border-gold-400/60'}`}>{prefix}{opt}</button>)}</div></div>}
