import { useEffect, useRef, useState } from 'react'
import { gsap } from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import SplitType from 'split-type'
import { ArrowDown, ArrowUpRight } from 'lucide-react'
import { track } from '../lib/analytics'

gsap.registerPlugin(ScrollTrigger)
export default function Hero(){
  const heroRef=useRef(null),titleRef=useRef(null),subtitleRef=useRef(null),ctaRef=useRef(null),mediaRef=useRef(null); const [mobile,setMobile]=useState(false)
  useEffect(()=>{const mq=window.matchMedia('(max-width:767px)');const sync=()=>setMobile(mq.matches);sync();mq.addEventListener?.('change',sync);return()=>mq.removeEventListener?.('change',sync)},[])
  useEffect(()=>{const ctx=gsap.context(()=>{const split=new SplitType(titleRef.current,{types:'lines,words',lineClass:'reveal-line'});gsap.set(split.words,{yPercent:110});gsap.set([subtitleRef.current,ctaRef.current],{opacity:0,y:26});gsap.set(mediaRef.current,{opacity:0,scale:1.02});gsap.timeline({delay:.05}).to(mediaRef.current,{opacity:1,scale:1,duration:1.35,ease:'power2.out'}).to(split.words,{yPercent:0,duration:1.25,ease:'expo.out',stagger:.055},'-=.95').to(subtitleRef.current,{opacity:1,y:0,duration:.85,ease:'expo.out'},'-=.8').to(ctaRef.current,{opacity:1,y:0,duration:.8,ease:'expo.out'},'-=.65');gsap.to(mediaRef.current,{scale:1.06,ease:'none',scrollTrigger:{trigger:heroRef.current,start:'top top',end:'bottom top',scrub:1}})},heroRef);return()=>ctx.revert()},[])
  const src=mobile?'/media/hero/hero-mobile.mp4':'/media/hero/hero-desktop.mp4',poster=mobile?'/media/hero/hero-mobile-poster.jpg':'/media/hero/hero-desktop-poster.jpg'
  return <section id="top" ref={heroRef} className="relative min-h-screen w-full overflow-hidden bg-navy-800 text-cream-200"><div ref={mediaRef} className="absolute inset-0"><video key={src} className="w-full h-full object-cover" autoPlay muted playsInline preload="auto" poster={poster}><source src={src} type="video/mp4"/></video></div><div className="absolute inset-0 hero-vignette"/><div className="absolute inset-0 hero-sidefade"/><div className="absolute top-0 inset-x-0 pt-28 md:pt-32 px-6 md:px-12 z-10"><div className="section-label text-cream-200/65 max-w-[1600px] mx-auto">ARQUITECTURA DE HORMIGÓN · READY TO LIVE</div></div><div className="relative z-10 min-h-screen flex flex-col justify-end px-6 md:px-12 pb-12 md:pb-20 max-w-[1600px] mx-auto"><div className="max-w-5xl"><h1 ref={titleRef} className="font-display text-hero leading-[.88] tracking-tightest">Tu casa.<br/>Ya <em className="italic text-gold-200 font-light">resuelta.</em></h1><p ref={subtitleRef} className="mt-7 md:mt-9 max-w-xl text-base md:text-lg text-cream-200/82 leading-relaxed">Viviendas industrializadas de hormigón, completamente equipadas y preparadas para vivir. Escoges el modelo. Nosotros hacemos el resto.</p></div><div ref={ctaRef} className="mt-9 md:mt-12 flex flex-col md:flex-row items-start md:items-center gap-5 md:gap-9"><a href="#models" onClick={()=>track('cta_click',{cta:'hero_collection'})} className="btn-primary group bg-cream-200 !text-navy-700"><span>Descubrir la colección</span><ArrowUpRight size={16}/></a><a href="#about" className="flex items-center gap-3 text-sm font-medium text-cream-200 link-underline"><span className="w-8 h-8 rounded-full border border-cream-200/35 flex items-center justify-center"><ArrowDown size={12}/></span>Descubre el concepto</a></div><div className="mt-10 md:mt-16 pt-5 border-t border-cream-200/20 flex justify-between section-label text-cream-200/60"><span>VORA · CONCRETE LIVING</span><span className="hidden md:inline">07 MODELOS · 90—245 M²</span></div></div></section>
}
