import { getPlanRooms } from '../data/houses'

function Furniture({ room }) {
  const x = room.x * 10, y = room.y * 6, w = room.w * 10, h = room.h * 6
  const light = '#d9d4ca', stroke = '#696b65', cx=x+w/2, cy=y+h/2
  if (room.type==='bedroom'||room.type==='suite') { const bw=Math.min(w*.58,170), bh=Math.min(h*.52,115); return <g opacity=".85"><rect x={cx-bw/2} y={cy-bh/2} width={bw} height={bh} rx="3" fill={light} stroke={stroke}/><rect x={cx-bw*.38} y={cy-bh*.38} width={bw*.76} height={bh*.25} rx="2" fill="#f1eee8" stroke={stroke}/><line x1={cx} y1={cy-bh/2} x2={cx} y2={cy+bh/2} stroke={stroke}/></g> }
  if (room.type==='living') return <g opacity=".82"><rect x={x+w*.1} y={y+h*.18} width={w*.45} height={Math.max(28,h*.18)} rx="8" fill={light} stroke={stroke}/><rect x={x+w*.18} y={y+h*.55} width={w*.34} height={Math.max(22,h*.13)} rx="10" fill="#b7ad9f" stroke={stroke}/><circle cx={x+w*.74} cy={y+h*.55} r={Math.min(26,w*.06)} fill="none" stroke={stroke}/><circle cx={x+w*.81} cy={y+h*.55} r={Math.min(26,w*.06)} fill="none" stroke={stroke}/></g>
  if (room.type==='kitchen') return <g opacity=".82"><rect x={x+w*.08} y={y+h*.1} width={w*.84} height={Math.max(18,h*.16)} fill={light} stroke={stroke}/><rect x={x+w*.25} y={y+h*.48} width={w*.5} height={Math.max(24,h*.22)} fill="#c7bba9" stroke={stroke}/></g>
  if (room.type==='bath') return <g opacity=".82"><rect x={x+w*.1} y={y+h*.12} width={w*.35} height={h*.32} fill="none" stroke={stroke}/><ellipse cx={x+w*.72} cy={y+h*.28} rx={Math.max(9,w*.08)} ry={Math.max(13,h*.11)} fill="none" stroke={stroke}/><rect x={x+w*.14} y={y+h*.64} width={w*.7} height={Math.max(10,h*.12)} fill={light} stroke={stroke}/></g>
  if (room.type==='closet') return <g opacity=".8"><rect x={x+w*.09} y={y+h*.1} width={w*.28} height={h*.8} fill={light} stroke={stroke}/><rect x={x+w*.63} y={y+h*.1} width={w*.28} height={h*.8} fill={light} stroke={stroke}/></g>
  if (room.type==='office'||room.type==='gym') return <g opacity=".82"><rect x={x+w*.18} y={y+h*.2} width={w*.64} height={Math.max(20,h*.16)} fill={light} stroke={stroke}/><circle cx={cx} cy={y+h*.58} r={Math.min(18,w*.08)} fill="none" stroke={stroke}/></g>
  if (['laundry','technical','pantry'].includes(room.type)) return <g opacity=".8"><rect x={x+w*.15} y={y+h*.2} width={w*.7} height={h*.6} fill={light} stroke={stroke}/></g>
  return null
}
function WindowMark({room}){ if(!room.window||room.window==='none') return null; const x=room.x*10,y=room.y*6,w=room.w*10,h=room.h*6; const len=['top','bottom'].includes(room.window)?Math.min(90,w*.52):Math.min(70,h*.52); const s='#b29d7c'; if(room.window==='top')return <line x1={x+w/2-len/2} x2={x+w/2+len/2} y1={y} y2={y} stroke={s} strokeWidth="7"/>; if(room.window==='bottom')return <line x1={x+w/2-len/2} x2={x+w/2+len/2} y1={y+h} y2={y+h} stroke={s} strokeWidth="7"/>; if(room.window==='left')return <line x1={x} x2={x} y1={y+h/2-len/2} y2={y+h/2+len/2} stroke={s} strokeWidth="7"/>; return <line x1={x+w} x2={x+w} y1={y+h/2-len/2} y2={y+h/2+len/2} stroke={s} strokeWidth="7"/> }
function DoorMark({room}){ if(!room.door||room.door==='none')return null; const x=room.x*10,y=room.y*6,w=room.w*10,h=room.h*6,r=26,s='#8e8d85'; if(room.door==='bottom')return <g><line x1={x+w*.18} x2={x+w*.18+r} y1={y+h} y2={y+h-r} stroke={s} strokeWidth="2"/><path d={`M ${x+w*.18+r} ${y+h} A ${r} ${r} 0 0 0 ${x+w*.18} ${y+h-r}`} fill="none" stroke={s}/></g>; if(room.door==='left')return <g><line x1={x} x2={x+r} y1={y+h*.22} y2={y+h*.22-r} stroke={s} strokeWidth="2"/></g>; return null }
export default function PlanView({model,furnished=true,showMeasurements=true}){
  const planRooms=getPlanRooms(model)
  return <div className="overflow-hidden bg-[#d7d5cf] p-3 md:p-6"><svg viewBox="-65 -60 1130 720" className="h-auto w-full" role="img" aria-label={furnished?'Plano amueblado conceptual':'Plano arquitectónico conceptual'}><rect x="0" y="0" width="1000" height="600" fill="#fbf8f2" stroke="#333530" strokeWidth="6"/>{planRooms.map((room,i)=>{const x=room.x*10,y=room.y*6,w=room.w*10,h=room.h*6;return <g key={`${room.roomId}-${i}`}><rect x={x} y={y} width={w} height={h} fill="#fbf8f2" stroke="#343630" strokeWidth="3"/>{furnished&&<Furniture room={room}/>}<WindowMark room={room}/><DoorMark room={room}/><text x={x+8} y={y+17} fontFamily="Arial, sans-serif" fontSize="10" fill="#30322e" fontWeight="600">{room.name.toUpperCase()}</text>{showMeasurements&&<text x={x+8} y={y+31} fontFamily="Arial, sans-serif" fontSize="9" fill="#6f7069">{room.area.toFixed(1).replace('.',',')} m²</text>}</g>})}{showMeasurements&&<><line x1="0" x2="1000" y1="-28" y2="-28" stroke="#8b8c85"/><text x="500" y="-36" textAnchor="middle" fontFamily="Arial" fontSize="13" fill="#555750">{model.plan.widthM.toFixed(1).replace('.',',')} m aprox.</text></>}<g transform="translate(940 540)"><path d="M0 35 L20 0 L40 35 Z" fill="#2c2e2a"/><text x="20" y="52" textAnchor="middle" fontFamily="Arial" fontSize="11">N</text></g></svg></div>
}
