import fs from 'node:fs/promises'
import path from 'node:path'
import { HOUSES } from '../src/data/houses.js'
const dist=path.resolve('dist');const base=process.env.VITE_SITE_URL||process.env.SITE_URL||'https://vora-orpin-delta.vercel.app';const template=await fs.readFile(path.join(dist,'index.html'),'utf8')
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))
const abs=u=>u.startsWith('http')?u:`${base}${u}`
function render({title,description,pathname='/',image='/media/houses/model-07-exterior.webp',content,schema,robots='index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1'}){
  let html=template.replace(/<title>.*?<\/title>/s,`<title>${esc(title)}</title>`).replace(/<meta name="description"[^>]*>/,`<meta name="description" content="${esc(description)}" />`)
  const canonical=`${base}${pathname==='/'?'':pathname}`
  const extra=`\n<link rel="canonical" href="${canonical}" />\n<meta name="robots" content="${robots}" />\n<meta property="og:type" content="website" />\n<meta property="og:locale" content="es_ES" />\n<meta property="og:site_name" content="VORA · Concrete Living" />\n<meta property="og:title" content="${esc(title)}" />\n<meta property="og:description" content="${esc(description)}" />\n<meta property="og:url" content="${canonical}" />\n<meta property="og:image" content="${abs(image)}" />\n<meta name="twitter:card" content="summary_large_image" />\n<meta name="twitter:title" content="${esc(title)}" />\n<meta name="twitter:description" content="${esc(description)}" />\n<meta name="twitter:image" content="${abs(image)}" />\n<script type="application/ld+json">${JSON.stringify(schema)}</script>\n`
  html=html.replace('</head>',extra+'</head>').replace('<div id="root"></div>',`<div id="root">${content}</div>`);return html
}
const org={"@type":"Organization","@id":`${base}/#organization`,name:'VORA',url:base,logo:abs('/vora-logo-dark.svg'),description:'Marca de viviendas industrializadas de hormigón completamente equipadas y preparadas para vivir.'}
const homeSchema={"@context":"https://schema.org","@graph":[org,{"@type":"WebSite","@id":`${base}/#website`,url:base,name:'VORA · Concrete Living',publisher:{"@id":`${base}/#organization`},inLanguage:'es'},{"@type":"ItemList",name:'Colección VORA',itemListElement:HOUSES.map((h,i)=>({"@type":"ListItem",position:i+1,url:`${base}/modelos/${h.id}`,name:`VORA ${h.name}`}))}]}
const homeContent=`<main style="min-height:100vh;background:#F0EEE9;color:#24231F;padding:48px;font-family:Arial,sans-serif"><h1>VORA · Concrete Living</h1><p>Viviendas industrializadas de hormigón, completamente equipadas y preparadas para vivir.</p><h2>Colección VORA</h2><ul>${HOUSES.map(h=>`<li><a href="/modelos/${h.id}">VORA ${esc(h.name)}</a> — ${esc(h.size)}, ${h.bedrooms} dormitorios, ${h.bathrooms} baños.</li>`).join('')}</ul><h2>Escoge tu casa. Nosotros hacemos el resto.</h2><p>Modelos cerrados con arquitectura, distribución, acabados y equipamiento concebidos como un único producto. Adaptamos técnicamente el modelo elegido a la parcela.</p></main>`
await fs.writeFile(path.join(dist,'index.html'),render({title:'VORA Concrete Living | Casas industrializadas de hormigón listas para vivir',description:'VORA crea viviendas industrializadas de hormigón de 90 a 245 m², completamente terminadas, equipadas y preparadas para vivir.',content:homeContent,schema:homeSchema}))
await fs.mkdir(path.join(dist,'modelos'),{recursive:true})
for(const h of HOUSES){const pathname=`/modelos/${h.id}`;const schema={"@context":"https://schema.org","@graph":[org,{"@type":"WebPage",url:`${base}${pathname}`,name:h.seoTitle,description:h.seoDescription,mainEntity:{"@type":"SingleFamilyResidence",name:`VORA ${h.name}`,description:h.description,image:[abs(h.image),abs(h.interior)],floorSize:{"@type":"QuantitativeValue",value:parseInt(h.size),unitCode:'MTK'},additionalProperty:[{"@type":"PropertyValue",name:'Dormitorios',value:h.bedrooms},{"@type":"PropertyValue",name:'Baños',value:h.bathrooms},{"@type":"PropertyValue",name:'Superficie útil',value:`${h.usableSurface} m²`},{"@type":"PropertyValue",name:'Porche',value:`${h.porchSurface} m²`}],amenityFeature:h.features.map(f=>({"@type":"LocationFeatureSpecification",name:f,value:true}))}}]};const content=`<main style="background:#F0EEE9;color:#24231F;padding:48px;font-family:Arial,sans-serif"><p>VORA · Concrete Living</p><h1>VORA ${esc(h.name)}</h1><p>${esc(h.description)}</p><p><strong>${esc(h.size)}</strong> · ${h.bedrooms} dormitorios · ${h.bathrooms} baños · ${h.usableSurface} m² útiles · porche ${h.porchSurface} m².</p><h2>Distribución</h2><ul>${h.rooms.map(r=>`<li>${esc(r.name)} — ${String(r.area).replace('.',',')} m²</li>`).join('')}</ul><h2>Ready to live</h2><p>Cocina, electrodomésticos, mobiliario principal, iluminación, baños, climatización, armarios e instalaciones forman parte de la propuesta del modelo.</p><p>Distribución orientativa sujeta a adaptación técnica, urbanística y estructural.</p><p><a href="/#contact">Estudiar mi parcela</a></p></main>`;await fs.writeFile(path.join(dist,'modelos',`${h.id}.html`),render({title:h.seoTitle,description:h.seoDescription,pathname,image:h.image,content,schema}))}
const landings={
'casas-industrializadas-hormigon':['Casas industrializadas de hormigón | VORA Concrete Living','Descubre viviendas industrializadas de hormigón de arquitectura contemporánea, modelos cerrados y equipamiento completo ready to live.'],
'casas-hormigon-llave-en-mano':['Casas de hormigón llave en mano y equipadas | VORA','Viviendas de hormigón construidas, terminadas, equipadas y amuebladas. Una experiencia ready to live desde la parcela hasta las llaves.'],
'casas-modulares-premium':['Casas modulares premium de hormigón | VORA','Colección premium de casas industrializadas de hormigón con diseño mediterráneo contemporáneo y equipamiento completo.']}
for(const [slug,[title,description]] of Object.entries(landings)){const content=`<main style="background:#F0EEE9;color:#24231F;padding:48px;font-family:Arial,sans-serif"><h1>${esc(title.split('|')[0])}</h1><p>${esc(description)}</p><h2>Qué diferencia a VORA</h2><p>Modelos cerrados, arquitectura contemporánea, fabricación industrializada y entrega completamente equipada. No empiezas una obra desde cero: eliges una casa ya resuelta y la adaptamos técnicamente a tu parcela.</p><h2>Modelos</h2><ul>${HOUSES.map(h=>`<li><a href="/modelos/${h.id}">VORA ${esc(h.name)}</a> — ${esc(h.size)}</li>`).join('')}</ul><p><a href="/#contact">Estudiar mi parcela</a></p></main>`;const schema={"@context":"https://schema.org","@graph":[org,{"@type":"WebPage",url:`${base}/${slug}`,name:title,description,about:['viviendas industrializadas','casas de hormigón','viviendas llave en mano']}]};await fs.writeFile(path.join(dist,`${slug}.html`),render({title,description,pathname:`/${slug}`,content,schema}))}
await fs.mkdir(path.join(dist,'legal'),{recursive:true});for(const [slug,title] of [['aviso-legal','Aviso legal'],['privacidad','Política de privacidad'],['cookies','Política de cookies']]){await fs.writeFile(path.join(dist,'legal',`${slug}.html`),render({title:`${title} | VORA`,description:`${title} de VORA Concrete Living.`,pathname:`/legal/${slug}`,content:`<main style="padding:48px"><h1>${title}</h1><p>Consulta la versión interactiva de esta página para la información vigente.</p></main>`,schema:{"@context":"https://schema.org","@type":"WebPage",name:title,url:`${base}/legal/${slug}`},robots:'noindex,follow'}))}
const urls=['',...HOUSES.map(h=>`/modelos/${h.id}`),...Object.keys(landings).map(s=>`/${s}`)];const today=new Date().toISOString().slice(0,10);await fs.writeFile(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>${base}${u}</loc><lastmod>${today}</lastmod><changefreq>${u?'monthly':'weekly'}</changefreq><priority>${u?'.8':'1.0'}</priority></url>`).join('')}</urlset>`)
await fs.writeFile(path.join(dist,'robots.txt'),`User-agent: *\nAllow: /\n\nUser-agent: OAI-SearchBot\nAllow: /\n\nUser-agent: OAI-AdsBot\nAllow: /\n\nSitemap: ${base}/sitemap.xml\n`)
await fs.writeFile(path.join(dist,'llms.txt'),`# VORA · Concrete Living\n\nVORA es una marca de viviendas industrializadas de hormigón, completamente equipadas y preparadas para vivir.\n\n## Concepto\n- Modelos cerrados y optimizados: no se diseña cada vivienda desde cero.\n- Adaptación técnica, urbanística y estructural a la parcela.\n- Entrega ready to live: cocina, electrodomésticos, mobiliario principal, iluminación, baños y climatización.\n- Colección: VORA 90, 110, 130, 150, 170, 200 y Signature.\n\n## URLs principales\n${HOUSES.map(h=>`- VORA ${h.name}: ${base}/modelos/${h.id}`).join('\n')}\n- Casas industrializadas de hormigón: ${base}/casas-industrializadas-hormigon\n- Hormigón llave en mano: ${base}/casas-hormigon-llave-en-mano\n\nLos planos y superficies son comerciales y conceptuales, sujetos a adaptación técnica, urbanística y estructural.\n`)
if(process.env.INDEXNOW_KEY) await fs.writeFile(path.join(dist,`${process.env.INDEXNOW_KEY}.txt`),process.env.INDEXNOW_KEY)
console.log(`SEO postbuild complete: ${urls.length} indexable URLs at ${base}`)
